### ISSUE TITLE
Gitignored files are included in some linter

### ISSUE THREAD

**Issue by kftsehk** [oxsecurity/megalinter#2764]
**Describe the bug**
Gitignored files are included in some linter

**To Reproduce**

`git init` and commit the following 2 files:

`.gitignore`
```
*/
*.py
```

`requirements.txt`
```
boto3
dynamodb_json
requests
requests_aws4auth
```

then run:
```
pip install -r requirements.txt -t .
docker run --rm \
    -e JAVASCRIPT_DEFAULT_STYLE=prettier \
    -e LINTER_RULES_PATH=/ \
    -e LOG_LEVEL=NOTICE \
    -e REPORT_OUTPUT_FOLDER=/tmp/megalinter-reports \
    -e RUN_LOCAL=true \
    -e ENABLE=ACTION,BASH,CLOUDFORMATION,CSS,DOCKERFILE,JAVASCRIPT,JSON,JSX,MAKEFILE,MARKDOWN,PYTHON,YAML \
    -e DISABLE_LINTERS=PYTHON_BANDIT,PYTHON_MYPY,PYTHON_PYRIGHT,PYTHON_RUFF \
    -e JAVASCRIPT_ES_FILE_EXTENSIONS=.js,.jsx,.graphql \
    -w /tmp/lint \
    -v "$(git rev-parse --show-toplevel)":/tmp/lint oxsecurity/megalinter-cupcake:latest
```

**Expected behavior**

_No file linted_

Only 2 files are not gitignored, none of which has a linter, namely
```
.gitignore
requirements.txt
```

**Screenshots**
```
+----MATCHING LINTERS-----------------------+---------------------+----------------+------------+
| Descriptor     | Linter                   | Criteria            | Matching files | Format/Fix |
+----------------+--------------------------+---------------------+----------------+------------+
| PYTHON         | pylint                   | .py                 | 282            | no         |
| PYTHON         | black                    | .py                 | 282            | no         |
| PYTHON         | flake8                   | .py                 | 282            | no         |
| PYTHON         | isort                    | .py                 | 282            | no         |
| CLOUDFORMATION | cfn-lint                 | .yml|.yaml|.json    | 14             | no         |
| JSON           | jsonlint                 | .json               | 1186           | no         |
| JSON           | eslint-plugin-jsonc      | .json|.json5|.jsonc | 1186           | no         |
| JSON           | v8r                      | .json               | 1186           | no         |
| JSON           | prettier                 | .json               | 1186           | no         |
| MARKDOWN       | markdownlint             | .md                 | 1              | no         |
| MARKDOWN       | markdown-link-check      | .md                 | 1              | no         |
| MARKDOWN       | markdown-table-formatter | .md                 | 1              | no         |
+----------------+--------------------------+---------------------+----------------+------------+
```

**Additional context**

If skip the `pip install` step, behavior is correct

![image](https://github.com/oxsecurity/megalinter/assets/20808792/0fd97f69-2b06-4161-b186-72da0cb5e2cc)

It is not always the case for all linter. E.g. in Javascript toolchain, ignoreing `node_modules/` does exclude everything inside every `node_modules/` to be linted

**Comment by cpotteck** [comment]
I've observed similar behaviour with [markdown-link-check](https://megalinter.io/latest/descriptors/markdown_markdown_link_check/), where it includes some files under `megalinter-reports/` and other directories which are listed in `.gitignore`, but not all, and it is not consistent.

**Comment by MRDGH2821** [comment]
I looked into devskim and found that it has a cli flag to ignore gitignored files

So I think megalinter should identify such flags & pass it onto linters, if the linter has such cli flag available

**Comment by bradthurber** [comment]
@nvuillam thank you for MegaLinter! Below is my current disabled linters list in v7.10 `.mega-linter.yml` because they seem to be linting in areas that are in `.gitignore`. Is it helpful to update this list if more are found?

```yaml
DISABLE_LINTERS:
  # The following linters seem to be digging around in folders they shouldn't. (areas in .gitignore)
  - COPYPASTE_JSCPD
  - REPOSITORY_DEVSKIM
  - REPOSITORY_TRIVY
  - YAML_YAMLLINT
  - REPOSITORY_SECRETLINT
 ```

**Comment by nvuillam** [comment]
@MRDGH2821 `--skip-git-ignored-files` is now natively sent to DevSkim by MegaLinter :)

@bradthurber I think the best would be to add documentation about how to add additional parameters ( _ARGUMENTS ) to ignore stuff :)

**Comment by Kurt-von-Laven** [comment]
@bradthurber if you are able to test this on the beta image, I think #2967 should have helped with this issue.

**Comment by nvuillam** [comment]
@bradthurber I confirm it's supposed to be solved with beta version (and in next release :) )

**Comment by bradthurber** [comment]
@Kurt-von-Laven and @nvuillam, I am happy to give this a shot with the beta version. Is there a doc somewhere with instructions to run the beta image using mega-linter-runner?

**Comment by nvuillam** [comment]
@bradthurber it has been tested, don't worry :)

ps: new release is very soon ^^

**Comment by echoix** [comment]
> @Kurt-von-Laven and @nvuillam, I am happy to give this a shot with the beta version. Is there a doc somewhere with instructions to run the beta image using mega-linter-runner?

In the mega-linter-runner README, there are examples using the `--release` argument, like: 

```
mega-linter-runner --flavor python --release beta
```

https://megalinter.io/latest/mega-linter-runner/#examples

**Comment by nvuillam** [comment]
I just released 7.4.0 :)

**Comment by nofoxsteven** [comment]
This still seems to be an issue in 7.4.0. At least `COPYPASTE_JSCPD` does still not respect folders excluded by .gitignore.

**Comment by nvuillam** [comment]
@noskovao as all linters working in project mode (and not with a list of files sent by MegaLinter), jscpd has its own way to ignore folders/files 

You can see how in MegaLinter page about jscpd :)

https://megalinter.io/latest/descriptors/copypaste_jscpd/

**Comment by burner1024** [comment]
> --skip-git-ignored-files is now natively sent to DevSkim by MegaLinter :)

@nvuillam
jscpd also has a flag for that. Shouldn't it be set by MegaLinter as well, or there's a reason to not do that?
`  -g, --gitignore            ignore all files from .gitignore file`

**Comment by nvuillam** [comment]
@burner1024 i didn't know about the flag, of course MegaLinter should send it by default, thanks :)

**Comment by MRDGH2821** [comment]
I feel that in megalinter website, the individual linter page can display a status marker of some sorts like:

Iinter supports gitignore flag: ✅
Megalinter passes the flag: ✅
